ds post

store
select * from store limit 50
df post
flow 02
[0]

tr post
[0]
[1]
tr get [2]
tr put [2]
append
rename col:store_code to:'a'
ds post
[1]
contract
select * from contract1 limit 50
tr post
[3]
[1]
tr get [4]
tr put [4]
append
rename col:product_01_code to:'p1'
tr put [4]
append
rename col:product_02_code to:'p2'
tr put [4]
append
rename col:product_03_code to:'p3'
tr put [4]
append
rename col:product_04_code to:'p4'
tr put [4]
append
merge col:p1,p2,p3,p4 with:'_' as:'prod_code'
