ds post

store 1/3 (2500)
select * from store limit 2500
ds post

store 2/3 (2500)
select * from store limit 2500
ds post

store 3/3 (2500)
select * from store limit 2500
df post
flow 08 (union)
[0]
[1]
[2]

tr post
[0]
[3]
tr post
[1]
[3]
tr post
[2]
[3]
tr put [4]
append
union masterCol: store_code, detail_store_code, customer_id dataset2: [5], [6]
ss post [4]
default
test_union

hdfs://localhost:9000/tmp/hdfsDir
