#########################
# create dataset: store #
#########################
ds post
store 52
select * from store limit 50
###################
# create dataflow #
###################
df post
flow 52
<store>

df get <flow>  # register store [W]
tr get <store>
tr put <store>
append
rename col: store_code to: a
tr get <store>
ss post <store>
default              # dbname
test_line_script_52  # table name
                     # partition keys
