#########################
# create dataset: store #
#########################
ds post
store 71
select * from default.store
###################
# create dataflow #
###################
df post
flow 71
<store>

df get <flow>  # register store [W]
tr get <store>
tr put <store>
append
rename col:store_code to:a
ss post <store>
default              # dbname
test_line_script_71  # table name
                     # partition keys
