ds post

product
select * from product limit 500
ds post

contract
select * from contract limit 1000
df post
store flow
[0]
[1]

tr post
[0]
[2]
tr post
[1]
[2]
tr put [3]
append
join leftSelectCol: product_name, product_01_code rightSelectCol: contract_id, product_01_code condition: product_01_code = product_01_code joinType:'inner' dataset2: [4]
ss post [3]
default
test_join

hdfs://localhost:9000/tmp/hdfsDir
